/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#c9e6ff",
        "outline": "#727785",
        "secondary": "#006591",
        "on-primary-container": "#fefcff",
        "on-secondary-container": "#004666",
        "tertiary-fixed-dim": "#b9c7e7",
        "surface-tint": "#005ac2",
        "on-surface-variant": "#424754",
        "on-error": "#ffffff",
        "outline-variant": "#c2c6d6",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-highest": "#d3e4ff",
        "on-tertiary-fixed": "#0c1b34",
        "surface-bright": "#f8f9ff",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#d7e2ff",
        "error-container": "#ffdad6",
        "surface-variant": "#d3e4ff",
        "on-tertiary-fixed-variant": "#394762",
        "surface": "#f8f9ff",
        "on-surface": "#001c38",
        "primary-fixed-dim": "#adc6ff",
        "secondary-fixed-dim": "#89ceff",
        "background": "#f8f9ff",
        "surface-container": "#e6eeff",
        "tertiary": "#4e5c78",
        "surface-container-low": "#eff4ff",
        "on-secondary-fixed": "#001e2f",
        "tertiary-container": "#677592",
        "surface-dim": "#c5dcff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#004c6e",
        "inverse-surface": "#113154",
        "on-background": "#001c38",
        "primary": "#0058be",
        "primary-fixed": "#d8e2ff",
        "surface-container-high": "#dde9ff",
        "secondary-container": "#39b8fd",
        "on-primary-fixed": "#001a42",
        "on-primary": "#ffffff",
        "inverse-primary": "#adc6ff",
        "on-primary-fixed-variant": "#004395",
        "primary-container": "#2170e4",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#fefcff"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "margin-desktop": "80px",
        "md": "16px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "sm": "8px",
        "xl": "48px",
        "base": "8px",
        "xs": "4px",
        "lg": "24px"
      },
    fontFamily: {
  "display-lg-mobile": ["-apple-system", "BlinkMacSystemFont", '"Segoe UI"', "Roboto", '"Helvetica Neue"', "Arial", "sans-serif"],
  "display-lg": ["-apple-system", "BlinkMacSystemFont", '"Segoe UI"', "Roboto", '"Helvetica Neue"', "Arial", "sans-serif"],
  "headline-md": ["-apple-system", "BlinkMacSystemFont", '"Segoe UI"', "Roboto", '"Helvetica Neue"', "Arial", "sans-serif"],
  "body-md": ["-apple-system", "BlinkMacSystemFont", '"Segoe UI"', "Roboto", '"Helvetica Neue"', "Arial", "sans-serif"],
  "body-lg": ["-apple-system", "BlinkMacSystemFont", '"Segoe UI"', "Roboto", '"Helvetica Neue"', "Arial", "sans-serif"],
  "label-sm": ["-apple-system", "BlinkMacSystemFont", '"Segoe UI"', "Roboto", '"Helvetica Neue"', "Arial", "sans-serif"],
},
      fontSize: {
        "display-lg-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
